//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementApp.Models
{
    using System;
    using System.Collections.Generic;
    using Repository.Pattern.Ef6;
    
    public partial class task: Entity
    {
        public int task_id { get; set; }
        public string task_name { get; set; }
        public int task_assignee { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
